# Generated by Django 3.0.6 on 2020-10-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Profile_img', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
